### ISSUE TITLE
species-web is down

### ISSUE THREAD

**Issue by beckerah** [NHMDenmark/Species-Web#2]
For the past week or so, when we try to access species-web in the browser, there is no data displayed. @bhsi-snm checked the server, which had an error that there was no space in the docker container. Charlotte is restarting digitization at AU today, therefore we need to sort this out quickly so Birgitte can view the images and approve the specimen data.

**Comment by bhsi-snm** [comment]
I have investigated that the server has 25Gb of space, which is all being used, so it cannot read any more data. We need to ask Aksel to increase the space on the server. 
There are 2 options:
Either we deploy it on our DeIC servers or ask Aksel to increase the space on the existing one.

what are your thoughts on it @PipBrewer

**Comment by PipBrewer** [comment]
Sent email to Aksel on 14/11/2024 requesting details for us to take over and pay for current Species-Web server

**Comment by beckerah** [comment]
Aksel increased the space on the server, but this is a temporary solution. We now need to back up the database and migrate everything over to a new server. I'll open a new issue for this.
